name: CI/CD pipeline

on:
  push:
    branches:
      - master

jobs:
  simple_pipeline:
    # set up the environment (same as we want to run in production)
    runs-on: ubuntu-20.04
    steps:
      # checkout the code from git repository, by default virtual env does not have any code in it
      - uses: actions/checkout@v3
      # set up node and define the version we want to use in production
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      # lint our code
      - name: lint
        run: npm run lint